import type { Metadata } from "next";
import { Geist, Geist_Mono, Open_Sans, Rubik } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import QueryProvider from "@/context/QueryProvider";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import StoreProvider from "@/context/StoreProvider";
import { Toaster } from "@/components/ui/sonner";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.variable} ${openSans.variable} antialiased`}>
        <ThemeProvider>
          <QueryProvider>
            <StoreProvider>
              <div className="font-rubik  flex flex-col min-h-screen bg-background text-foreground transition-colors duration-300">
                <Navbar />
                <main className="grow">{children}</main>
                <Footer />
              </div>
              <Toaster position="top-right" />
            </StoreProvider>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
